[package]
name = "zero_configure"
version = "0.1.0"
authors = ["Chris Macklin <chris.macklin@gmail.com>"]
edition = "2021"

[dependencies]
async-dnssd = "^0.4"
tokio-core = "^0.1"
futures = "^0.1"
zmq = "0.10.0"
serde = { version = "1", features = ["derive"] }
rmp-serde = "1.1.1"
anyhow = "1.0.70"
