[package]
name = "tunnels"
version = "0.1.0"
authors = ["general electrix <general.electrix@gmail.com>"]
edition = "2021"

[lib]
name = "tunnels"
path = "src/lib.rs"

[[bin]]
name = "tunnels"
path = "src/bin/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1", features = ["derive"]}
log = "^0.4"
simplelog = "0.12.0"
derive_more = "^0.99"
midir = "0.9.1"
simple-error = "0.3.0"
lazy_static = "^1"
typed_index_derive = "0.1.4"
zmq = "0.10.0"
tunnels_lib = { path = "../tunnels_lib" }
rmp-serde = "1.1.1"
rosc = "0.9.1"

zero_configure = { path = "../zero_configure" }

# Audio subsystem
cpal = "0.15.1"
augmented-dsp-filters = "1.3.1"
audio-processor-analysis = "0.4.0"
audio-processor-traits = "2.2.0"
augmented-atomics = "0.1.1"

[dev-dependencies]
insta = { version = "1.28.0", features = ["yaml"] }
plotters = "^0.3.0"
