[package]
name = "tunnels"
version = "0.1.0"
authors = ["general electrix <general.electrix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1", features = ["derive"]}
log = "^0.4"
simplelog = "^0.10"
derive_more = "^0.99"
midir = "^0.7"
simple-error = "^0.2"
lazy_static = "^1"
typed_index_derive = "0.1.4"
zmq = "0.9"
tunnels_lib = { path = "../tunnels_lib" }
rmp-serde = "0.15"
rosc = "~0.8"

# Audio subsystem
cpal = { git = "https://github.com/RustAudio/cpal", rev = "def424809b659c52902e8796d983c059f39b0e06"}
augmented-dsp-filters = "1.1.0"
audio-processor-analysis = "0.2.0"
audio-processor-traits = "1.1.0"
augmented-atomics = "0.1.1"

[dev-dependencies]
insta = { version = "1.28.0", features = ["yaml"] }
plotters = "^0.3.0"
