[package]
name = "tunnels"
version = "0.1.0"
authors = ["general electrix <general.electrix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1", features = ["derive"]}
log = "^0.4"
simplelog = "^0.10"
derive_more = "^0.99"
midir = "^0.7"
simple-error = "^0.2"
lazy_static = "^1"
typed_index_derive = "0.1.4"
zmq = "0.9"
tunnels_lib = { path = "../tunnels_lib" }
rmp-serde = "0.15"
plotters = "^0.3.0"
# rosc = "~0.8"