//! Set every curated figure against the output of the Python generator it was
//! ported from.
//!
//! The Python emits straight-line polylines at two decimals, so a figure that
//! agrees exactly in double precision agrees to within half of the last digit
//! kept — 0.005. The tolerance below is that bound plus a little slack for the
//! last bit of a trigonometric result, and the report prints the deviation
//! actually observed so the slack can be checked rather than trusted.
//!
//! Circles are the exception: the generator writes them as arcs, which have no
//! points to compare against. Those are checked against the circle itself —
//! every vertex on it, and the walk going all the way round.

mod support;

use std::collections::BTreeMap;
use std::f64::consts::{PI, TAU};
use support::{Recorded, Subpath, format_figure, parse_path_data, python_svg_dir, read_path_data};
use tunnels_shapes::geom::Figure;
use tunnels_shapes::presets;

/// Half of the last decimal the SVGs keep, plus slack for a last-bit difference
/// in a trigonometric result.
const TOLERANCE: f64 = 0.006;

#[derive(Default)]
struct FamilyReport {
    exact: usize,
    within_tolerance: usize,
    worst_deviation: f64,
    mismatches: Vec<String>,
}

#[test]
fn matches_the_python_generator() {
    let Some(dir) = python_svg_dir() else {
        // The always-on gate is `matches_the_recorded_python_output`; this test
        // is the same comparison with the whole figure to hand to report from.
        println!(
            "skipped: the Python generator's SVGs were not found. Set \
             TUNNELS_SHAPES_PYTHON_SVGS to the directory holding them."
        );
        return;
    };

    let mut families: BTreeMap<&'static str, FamilyReport> = BTreeMap::new();
    for preset in presets::all() {
        let report = families.entry(preset.params.family().name()).or_default();
        let path = dir.join(format!("{}.svg", preset.name));
        let svg = match std::fs::read_to_string(&path) {
            Ok(svg) => svg,
            Err(e) => {
                report.mismatches.push(format!("{}: {e}", preset.name));
                continue;
            }
        };
        let figure = preset.params.generate();
        match compare(&svg, &figure) {
            Ok(Comparison::Exact) => report.exact += 1,
            Ok(Comparison::Close(deviation)) => {
                report.within_tolerance += 1;
                report.worst_deviation = report.worst_deviation.max(deviation);
            }
            Err(reason) => report.mismatches.push(format!("{}: {reason}", preset.name)),
        }
    }

    let mut failures = Vec::new();
    for uncovered in uncovered_shapes(&dir) {
        failures.push(format!(
            "{uncovered}: generated by the Python, but no preset builds it"
        ));
    }
    println!(
        "\n{:<14} {:>6} {:>8} {:>10}  mismatches",
        "family", "exact", "within", "worst dev"
    );
    for (family, report) in &families {
        println!(
            "{family:<14} {:>6} {:>8} {:>10.5}  {}",
            report.exact,
            report.within_tolerance,
            report.worst_deviation,
            report.mismatches.len()
        );
        for mismatch in &report.mismatches {
            failures.push(mismatch.clone());
        }
    }
    assert!(
        failures.is_empty(),
        "figures disagree with the Python:\n  {}",
        failures.join("\n  ")
    );
}

/// Figures the Python wrote that no preset accounts for.
///
/// The generator also writes glyphs traced from fonts, which have no procedural
/// parameters to port; those are named for where they came from.
fn uncovered_shapes(dir: &std::path::Path) -> Vec<String> {
    const ASSET_PREFIXES: [&str; 2] = ["db_", "wm_"];
    let covered: std::collections::HashSet<String> =
        presets::all().into_iter().map(|p| p.name).collect();
    let mut uncovered: Vec<String> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .filter_map(|entry| {
            let name = entry.file_name().to_string_lossy().into_owned();
            let stem = name.strip_suffix(".svg")?;
            let is_asset = ASSET_PREFIXES.iter().any(|p| stem.starts_with(p));
            (!is_asset && !covered.contains(stem)).then(|| stem.to_string())
        })
        .collect();
    uncovered.sort();
    uncovered
}

enum Comparison {
    Exact,
    Close(f64),
}

fn compare(svg: &str, figure: &Figure) -> Result<Comparison, String> {
    let d = read_path_data(svg)?;
    if format_figure(figure) == d {
        return Ok(Comparison::Exact);
    }
    let subpaths = parse_path_data(d)?;
    if subpaths.len() != figure.contours.len() {
        return Err(format!(
            "{} subpaths in the SVG, {} contours generated",
            subpaths.len(),
            figure.contours.len()
        ));
    }
    let mut worst: f64 = 0.0;
    for (i, (subpath, contour)) in subpaths.iter().zip(&figure.contours).enumerate() {
        let deviation = match subpath {
            Subpath::Poly(points) => compare_poly(points, contour.points())?,
            Subpath::Circle { cx, cy, r } => compare_circle(*cx, *cy, *r, contour.points())?,
        };
        if deviation > TOLERANCE {
            return Err(format!("subpath {i} is off by {deviation:.4}"));
        }
        worst = worst.max(deviation);
    }
    Ok(Comparison::Close(worst))
}

fn compare_poly(
    expected: &[(f64, f64)],
    actual: &[tunnels_shapes::geom::Point],
) -> Result<f64, String> {
    if expected.len() != actual.len() {
        return Err(format!(
            "{} points in the SVG, {} generated",
            expected.len(),
            actual.len()
        ));
    }
    Ok(expected
        .iter()
        .zip(actual)
        .map(|(&(x, y), p)| (p.x - x).abs().max((p.y - y).abs()))
        .fold(0.0, f64::max))
}

/// Check a flattened circle against the arc the generator wrote in its place.
///
/// Every vertex must sit on the circle, and the steps between them must add up
/// to one full turn, which together say the polyline is that circle and not an
/// arc of it. The turn is signed, so a circle walked either way passes and a
/// circle that doubles back does not.
fn compare_circle(
    cx: f64,
    cy: f64,
    r: f64,
    actual: &[tunnels_shapes::geom::Point],
) -> Result<f64, String> {
    if actual.len() < 3 {
        return Err(format!("{} points is not a circle", actual.len()));
    }
    let mut worst: f64 = 0.0;
    let mut turned = 0.0;
    for (i, p) in actual.iter().enumerate() {
        let (dx, dy) = (p.x - cx, p.y - cy);
        worst = worst.max((dx.hypot(dy) - r).abs());
        let next = actual[(i + 1) % actual.len()];
        let step = (next.y - cy).atan2(next.x - cx) - dy.atan2(dx);
        turned += (step + PI).rem_euclid(TAU) - PI;
    }
    if (turned.abs() - TAU).abs() > 1e-9 {
        return Err(format!("walks {:.3} turns, not one", turned.abs() / TAU));
    }
    Ok(worst)
}

/// No figure may carry a coordinate that is not a number.
///
/// A degenerate parameter reaching a tessellator as a NaN takes the frame with
/// it, and this code runs while an audience is watching.
#[test]
fn every_coordinate_is_finite() {
    for preset in presets::all() {
        for p in preset
            .params
            .generate()
            .contours
            .iter()
            .flat_map(|c| c.points())
        {
            assert!(
                p.x.is_finite() && p.y.is_finite(),
                "{} carries a coordinate that is not finite",
                preset.name
            );
        }
    }
}

/// A digest of the Python's output for every preset, so the port stays checked
/// against it once the generator's SVGs are no longer to hand.
///
/// This is a gate only because every polyline family reproduces the Python's
/// path data byte for byte: a digest can say "identical" and nothing else. A
/// family that ever lands within tolerance rather than exact has no digest that
/// can hold it, and would need a fixture carrying its points — so a family
/// moving from the `exact` column to the `within` column in the report above is
/// a signal to change the fixture, not to widen anything.
const MANIFEST: &str = include_str!("fixtures/python_digest.tsv");

#[test]
fn matches_the_recorded_python_output() {
    let recorded: BTreeMap<&str, Recorded> = MANIFEST
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let mut fields = line.split('\t');
            let mut next = || fields.next().unwrap_or_default();
            let (name, kind, body) = (next(), next(), next());
            (
                name,
                Recorded::decode(kind, body).unwrap_or_else(|e| panic!("{name}: {e}")),
            )
        })
        .collect();

    let presets = presets::all();
    let mut failures = Vec::new();
    for preset in &presets {
        let Some(expected) = recorded.get(preset.name.as_str()) else {
            failures.push(format!("{}: not in the manifest", preset.name));
            continue;
        };
        if let Err(reason) = check_recorded(&preset.params.generate(), expected) {
            failures.push(format!("{}: {reason}", preset.name));
        }
    }
    assert!(
        failures.is_empty(),
        "figures disagree with the recorded Python output:\n  {}",
        failures.join("\n  ")
    );
    assert_eq!(
        recorded.len(),
        presets.len(),
        "the manifest and the preset list are different sizes"
    );
}

fn check_recorded(figure: &Figure, expected: &Recorded) -> Result<(), String> {
    match expected {
        Recorded::Poly(want) => {
            let got = support::digest(&format_figure(figure));
            (got == *want)
                .then_some(())
                .ok_or_else(|| format!("path data digest {got:032x}, recorded {want:032x}"))
        }
        Recorded::Circles(circles) => {
            if circles.len() != figure.contours.len() {
                return Err(format!(
                    "{} circles recorded, {} contours generated",
                    circles.len(),
                    figure.contours.len()
                ));
            }
            for (&(cx, cy, r), contour) in circles.iter().zip(&figure.contours) {
                let deviation = compare_circle(cx, cy, r, contour.points())?;
                if deviation > TOLERANCE {
                    return Err(format!("a vertex is {deviation:.4} off its circle"));
                }
            }
            Ok(())
        }
    }
}

/// Rebuild the manifest from the Python generator's SVGs.
///
/// Ignored because it needs the generator's output, which lives in the curation
/// checkout rather than in this one.
#[test]
#[ignore = "needs the Python generator's SVGs"]
fn regenerate_manifest() {
    let dir = python_svg_dir().expect("set TUNNELS_SHAPES_PYTHON_SVGS to the generator's output");
    let mut out = String::from(
        "# The Python generator's output per preset: a digest of the path data, or\n\
         # the circles it wrote as arcs. Rebuild with `cargo test regenerate_manifest\n\
         # -- --ignored`.\n",
    );
    for preset in presets::all() {
        let svg = std::fs::read_to_string(dir.join(format!("{}.svg", preset.name)))
            .unwrap_or_else(|e| panic!("{}: {e}", preset.name));
        let d = read_path_data(&svg).unwrap_or_else(|e| panic!("{}: {e}", preset.name));
        let recorded = Recorded::of(d).unwrap_or_else(|e| panic!("{}: {e}", preset.name));
        out.push_str(&format!("{}\t{}\n", preset.name, recorded.encode()));
    }
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/python_digest.tsv");
    std::fs::write(&path, out).expect("write the manifest");
}
