# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: draw_commands.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='draw_commands.proto',
  package='draw_commands',
  serialized_pb=_b('\n\x13\x64raw_commands.proto\x12\rdraw_commands\"\xa3\x01\n\x03\x41rc\x12\r\n\x05level\x18\x01 \x02(\r\x12\x15\n\rstroke_weight\x18\x02 \x02(\x02\x12\x0b\n\x03hue\x18\x03 \x02(\x02\x12\x0b\n\x03sat\x18\x04 \x02(\x02\x12\x0b\n\x03val\x18\x05 \x02(\r\x12\t\n\x01x\x18\x06 \x02(\x11\x12\t\n\x01y\x18\x07 \x02(\x11\x12\r\n\x05rad_x\x18\x08 \x02(\r\x12\r\n\x05rad_y\x18\t \x02(\r\x12\r\n\x05start\x18\n \x02(\x02\x12\x0c\n\x04stop\x18\x0b \x02(\x02\"0\n\x0c\x44rawCommands\x12 \n\x04\x61rcs\x18\x01 \x03(\x0b\x32\x12.draw_commands.Arc')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ARC = _descriptor.Descriptor(
  name='Arc',
  full_name='draw_commands.Arc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='draw_commands.Arc.level', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stroke_weight', full_name='draw_commands.Arc.stroke_weight', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hue', full_name='draw_commands.Arc.hue', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sat', full_name='draw_commands.Arc.sat', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='draw_commands.Arc.val', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='draw_commands.Arc.x', index=5,
      number=6, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='draw_commands.Arc.y', index=6,
      number=7, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rad_x', full_name='draw_commands.Arc.rad_x', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rad_y', full_name='draw_commands.Arc.rad_y', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='draw_commands.Arc.start', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop', full_name='draw_commands.Arc.stop', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=202,
)


_DRAWCOMMANDS = _descriptor.Descriptor(
  name='DrawCommands',
  full_name='draw_commands.DrawCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arcs', full_name='draw_commands.DrawCommands.arcs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=252,
)

_DRAWCOMMANDS.fields_by_name['arcs'].message_type = _ARC
DESCRIPTOR.message_types_by_name['Arc'] = _ARC
DESCRIPTOR.message_types_by_name['DrawCommands'] = _DRAWCOMMANDS

Arc = _reflection.GeneratedProtocolMessageType('Arc', (_message.Message,), dict(
  DESCRIPTOR = _ARC,
  __module__ = 'draw_commands_pb2'
  # @@protoc_insertion_point(class_scope:draw_commands.Arc)
  ))
_sym_db.RegisterMessage(Arc)

DrawCommands = _reflection.GeneratedProtocolMessageType('DrawCommands', (_message.Message,), dict(
  DESCRIPTOR = _DRAWCOMMANDS,
  __module__ = 'draw_commands_pb2'
  # @@protoc_insertion_point(class_scope:draw_commands.DrawCommands)
  ))
_sym_db.RegisterMessage(DrawCommands)


# @@protoc_insertion_point(module_scope)
