//! Run a blocking operation on a background thread with an egui progress modal.
//!
//! The task slot lives at the app level — one slot shared by all panels.
//! Each panel dispatches tasks via [`GuiContext::dispatch`], providing a
//! closure typed to its own state. The [`Project`] trait (generated by
//! [`impl_project!`]) handles the projection from app state to panel state.
//!
//! ```ignore
//! // App-level setup:
//! struct MyApp {
//!     task: Option<BlockingBackgroundTask<Self>>,
//!     panel_a: PanelA,
//!     modal: MessageModal,
//! }
//!
//! impl_project!(MyApp, panel_a: PanelA);
//!
//! // In MyApp::update, poll first, then dispatch:
//! if let Some(err) = self.task.poll(ctx).if_complete(self) {
//!     self.modal.show_error(err);
//! }
//!
//! // Panel dispatch (inside panel render, which receives GuiContext):
//! gui.dispatch::<PanelA, _>(
//!     "Doing work",
//!     move || do_blocking_work(),
//!     |panel, value| panel.handle_result(value),
//! );
//! ```

use std::any::Any;
use std::sync::{Arc, Mutex};
use std::thread;

use eframe::egui;

use crate::UserNotify;

/// Projection from an app-level state type to a panel-level state type.
///
/// Generated by [`impl_project!`]. Allows the background task infrastructure
/// to route success closures to the correct panel state.
pub trait Project<Sub> {
    fn project(&mut self) -> &mut Sub;
}

/// Generate a [`Project`] impl that projects from an app struct to one of its fields.
///
/// ```ignore
/// impl_project!(ConfigApp, projector_panel: ProjectorPanelState);
/// impl_project!(ConfigApp, admin_panel: AdminPanelState);
/// ```
#[macro_export]
macro_rules! impl_project {
    ($app:ty, $field:ident : $sub:ty) => {
        impl $crate::background_task::Project<$sub> for $app {
            fn project(&mut self) -> &mut $sub {
                &mut self.$field
            }
        }
    };
}

/// A blocking operation running on a background thread.
///
/// Generic only over `App` (the top-level state type), not over the success
/// value `T` — that is type-erased internally so a single task slot can hold
/// any kind of task.
///
/// Store as `Option<BlockingBackgroundTask<App>>` on your app state.
pub struct BlockingBackgroundTask<App> {
    label: String,
    /// `None` = thread still running. `Some` = thread finished.
    outcome: TaskOutcome,
    /// Called with `&mut App` and the type-erased success value.
    handler: Option<OnSuccess<App>>,
}

type TaskOutcome = Arc<Mutex<Option<Result<Box<dyn Any + Send>, anyhow::Error>>>>;
type OnSuccess<App> = Box<dyn FnOnce(&mut App, Box<dyn Any + Send>)>;

impl<App> BlockingBackgroundTask<App> {
    /// Spawn a background thread to execute `work`.
    ///
    /// On success, `on_success` is called with `&mut App` and the value `T`.
    /// The `T` type is erased internally — the task slot doesn't need to know
    /// what type each task produces.
    ///
    /// Errors are returned from [`PollResult::if_complete`] for the caller to
    /// display via [`MessageModal::show_error`].
    pub fn new<T: Send + 'static>(
        label: impl Into<String>,
        work: impl FnOnce() -> Result<T, anyhow::Error> + Send + 'static,
        on_success: impl FnOnce(&mut App, T) + 'static,
    ) -> Self {
        let label = label.into();
        let outcome: TaskOutcome = Arc::new(Mutex::new(None));
        let thread_outcome = outcome.clone();
        thread::spawn(move || {
            let result = work().map(|v| Box::new(v) as Box<dyn Any + Send>);
            *thread_outcome.lock().unwrap() = Some(result);
        });
        Self {
            label,
            outcome,
            handler: Some(Box::new(
                move |app: &mut App, boxed: Box<dyn Any + Send>| {
                    let value = *boxed
                        .downcast::<T>()
                        .expect("type mismatch in background task");
                    on_success(app, value);
                },
            )),
        }
    }

    /// Create a task with a success closure projected to a sub-state.
    ///
    /// This is the method called by [`GuiContext::dispatch`] — it wraps
    /// `on_success` so it receives `&mut Sub` instead of `&mut App`.
    pub fn projected<Sub, T: Send + 'static>(
        label: impl Into<String>,
        work: impl FnOnce() -> Result<T, anyhow::Error> + Send + 'static,
        on_success: impl FnOnce(&mut Sub, T) + 'static,
    ) -> Self
    where
        App: Project<Sub>,
    {
        Self::new(label, work, move |app: &mut App, value: T| {
            on_success(app.project(), value);
        })
    }
}

/// Returned by [`OptionTaskExt::poll`]. Must be consumed via
/// [`if_complete`](PollResult::if_complete).
#[must_use = "call .if_complete(app_state) to apply the task result"]
pub struct PollResult<App> {
    inner: Option<CompletedTask<App>>,
}

enum CompletedTask<App> {
    Success {
        value: Box<dyn Any + Send>,
        handler: OnSuccess<App>,
    },
    Error(anyhow::Error),
}

impl<App: UserNotify> PollResult<App> {
    /// Apply the completed task's result to the app state.
    ///
    /// On success: calls the stored `on_success` closure.
    /// On error: calls `state.notify_error(err)`.
    /// Not yet complete: no-op.
    pub fn if_complete(self, state: &mut App) {
        match self.inner {
            Some(CompletedTask::Success { value, handler }) => handler(state, value),
            Some(CompletedTask::Error(e)) => state.notify_error(e),
            None => {}
        }
    }
}

/// Extension trait on `Option<BlockingBackgroundTask<App>>` for ergonomic polling.
pub trait OptionTaskExt<App> {
    /// Draw the progress modal and check for completion.
    ///
    /// ```ignore
    /// if let Some(err) = self.task.poll(ctx).if_complete(self) {
    ///     self.modal.show_error(err);
    /// }
    /// ```
    ///
    /// - Idle (`None`): draws nothing.
    /// - Running: draws a modal spinner with Cancel button (blocks all interaction).
    /// - Just completed: packages the result for `.if_complete()`.
    fn poll(&mut self, ctx: &egui::Context) -> PollResult<App>;
}

impl<App> OptionTaskExt<App> for Option<BlockingBackgroundTask<App>> {
    fn poll(&mut self, ctx: &egui::Context) -> PollResult<App> {
        let empty = PollResult { inner: None };

        let Some(task) = self.as_mut() else {
            return empty;
        };

        // Check if the thread has produced a result.
        let outcome = task.outcome.lock().unwrap().take();

        let Some(result) = outcome else {
            // Still running — draw a modal that blocks all interaction behind it.
            // NOTE: egui::Modal is scoped to the current viewport. If we ever
            // dispatch tasks from a secondary window (e.g. detached visualizer),
            // we'll need to rethink this.
            let label = task.label.clone();
            let mut cancelled = false;
            let response =
                egui::Modal::new(egui::Id::new("background_task_progress")).show(ctx, |ui| {
                    ui.set_width(250.0);
                    ui.label(format!("{label}..."));
                    ui.add_space(8.0);
                    ui.spinner();
                    ui.add_space(4.0);
                    if ui.button("Cancel").clicked() {
                        cancelled = true;
                        ui.close();
                    }
                });
            if cancelled || response.should_close() {
                *self = None;
            } else {
                ctx.request_repaint();
            }
            return empty;
        };

        // Task completed — clear the slot and package the result.
        let handler = task
            .handler
            .take()
            .expect("on_success handler should be present");
        *self = None;

        PollResult {
            inner: Some(match result {
                Ok(value) => CompletedTask::Success { value, handler },
                Err(e) => CompletedTask::Error(e),
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::time::Duration;

    struct TestApp {
        panel: TestPanel,
        last_error: Option<String>,
    }

    struct TestPanel {
        value: Option<String>,
    }

    impl Project<TestPanel> for TestApp {
        fn project(&mut self) -> &mut TestPanel {
            &mut self.panel
        }
    }

    impl UserNotify for TestApp {
        fn notify(&mut self, _title: &str, _message: &str) {}
        fn notify_error(&mut self, error: anyhow::Error) {
            self.last_error = Some(format!("{error}"));
        }
    }

    fn test_app() -> TestApp {
        TestApp {
            panel: TestPanel { value: None },
            last_error: None,
        }
    }

    #[test]
    fn success_applies_closure() {
        let mut app = test_app();
        let mut task: Option<BlockingBackgroundTask<TestApp>> =
            Some(BlockingBackgroundTask::projected(
                "test",
                || Ok("hello".to_string()),
                |panel: &mut TestPanel, val| panel.value = Some(val),
            ));

        // Wait for the thread to finish.
        std::thread::sleep(Duration::from_millis(100));

        // Poll without egui context — just check the outcome directly.
        let outcome = task.as_mut().unwrap().outcome.lock().unwrap().take();
        assert!(outcome.is_some());
        let result = outcome.unwrap();
        assert!(result.is_ok());

        // Simulate what poll + if_complete does.
        let handler = task.as_mut().unwrap().handler.take().unwrap();
        let value = result.unwrap();
        handler(&mut app, value);

        assert_eq!(app.panel.value.as_deref(), Some("hello"));
    }

    #[test]
    fn error_is_returned() {
        let mut task: Option<BlockingBackgroundTask<TestApp>> =
            Some(BlockingBackgroundTask::projected::<TestPanel, ()>(
                "test",
                || anyhow::bail!("something broke"),
                |_, ()| {},
            ));

        std::thread::sleep(Duration::from_millis(100));

        let outcome = task.as_mut().unwrap().outcome.lock().unwrap().take();
        let result = outcome.unwrap();
        assert!(result.is_err());
        assert_eq!(format!("{}", result.unwrap_err()), "something broke");
    }

    #[test]
    fn if_complete_applies_success() {
        let completed: PollResult<TestApp> = PollResult {
            inner: Some(CompletedTask::Success {
                value: Box::new("hello".to_string()),
                handler: Box::new(|app: &mut TestApp, boxed| {
                    let val = *boxed.downcast::<String>().unwrap();
                    app.panel.value = Some(val);
                }),
            }),
        };
        let mut app = test_app();
        completed.if_complete(&mut app);
        assert_eq!(app.panel.value.as_deref(), Some("hello"));
        assert!(app.last_error.is_none());
    }

    #[test]
    fn if_complete_notifies_error() {
        let completed: PollResult<TestApp> = PollResult {
            inner: Some(CompletedTask::Error(anyhow::anyhow!("failed"))),
        };
        let mut app = test_app();
        completed.if_complete(&mut app);
        assert_eq!(app.last_error.as_deref(), Some("failed"));
    }

    #[test]
    fn if_complete_noop_when_idle() {
        let empty: PollResult<TestApp> = PollResult { inner: None };
        let mut app = test_app();
        empty.if_complete(&mut app);
        assert!(app.last_error.is_none());
        assert!(app.panel.value.is_none());
    }

    #[test]
    fn projected_routes_to_substate() {
        let task: BlockingBackgroundTask<TestApp> = BlockingBackgroundTask::projected(
            "test",
            || Ok(42i32),
            |panel: &mut TestPanel, val| panel.value = Some(val.to_string()),
        );

        std::thread::sleep(Duration::from_millis(100));

        let outcome = task.outcome.lock().unwrap().take().unwrap();
        let value = outcome.unwrap();
        let handler = task.handler.unwrap();

        let mut app = test_app();
        handler(&mut app, value);
        assert_eq!(app.panel.value.as_deref(), Some("42"));
    }

    #[test]
    fn work_runs_on_background_thread() {
        let started = Arc::new(AtomicBool::new(false));
        let started_clone = started.clone();

        let _task: BlockingBackgroundTask<TestApp> = BlockingBackgroundTask::new(
            "test",
            move || {
                started_clone.store(true, Ordering::SeqCst);
                Ok(())
            },
            |_, ()| {},
        );

        std::thread::sleep(Duration::from_millis(100));
        assert!(started.load(Ordering::SeqCst));
    }
}
