use gui_common::background_task::{BlockingBackgroundTask, Project};
use gui_common::MessageModal;
use gui_common::UserNotify;
use tunnels::control::{CommandClient, MetaCommand};

/// Shared rendering context for GUI panels.
///
/// Bundles the dependencies common to all panel renderers so they don't
/// need to be threaded through every method call.
///
/// `App` is the top-level application state type (e.g. `ConfigApp`).
/// Panels dispatch background tasks via [`dispatch`](Self::dispatch),
/// providing closures typed to their own state. The [`Project`] trait
/// handles projection from `App` to the panel's state type.
pub(crate) struct GuiContext<'a, App> {
    pub modal: &'a mut MessageModal,
    pub client: &'a CommandClient,
    pub task: &'a mut Option<BlockingBackgroundTask<App>>,
}

impl<App: 'static> GuiContext<'_, App> {
    pub fn report_error(&mut self, error: impl std::fmt::Display) {
        self.modal.show("Error", error.to_string());
    }

    pub fn send_command(&mut self, cmd: MetaCommand) -> Result<(), anyhow::Error> {
        match self.client.send_command(cmd) {
            Ok(()) => Ok(()),
            Err(e) => {
                self.modal.show("Error", e.to_string());
                Err(e)
            }
        }
    }

    /// Dispatch a blocking operation on a background thread.
    ///
    /// `Sub` is the panel state type — must have a [`Project`] impl mapping
    /// from `App` to `Sub` (generated by [`impl_project!`]).
    ///
    /// `on_success` receives `&mut Sub` and the value `T` when the work
    /// completes. Errors are shown in a modal automatically.
    pub fn dispatch<Sub, T: Send + 'static>(
        &mut self,
        label: impl Into<String>,
        work: impl FnOnce() -> Result<T, anyhow::Error> + Send + 'static,
        on_success: impl FnOnce(&mut Sub, T) + 'static,
    ) where
        App: Project<Sub>,
    {
        if !self.guard_dispatch() {
            return;
        }
        *self.task = Some(BlockingBackgroundTask::projected(label, work, on_success));
    }

    /// Dispatch a blocking operation that produces a success message.
    ///
    /// On success, the returned `String` is shown in the [`MessageModal`]
    /// as a "Success" notification. On error, the error is shown via
    /// `if_complete` at the app level.
    pub fn dispatch_notify(
        &mut self,
        label: impl Into<String>,
        work: impl FnOnce() -> Result<String, anyhow::Error> + Send + 'static,
    ) where
        App: UserNotify + 'static,
    {
        if !self.guard_dispatch() {
            return;
        }
        *self.task = Some(BlockingBackgroundTask::new(
            label,
            work,
            |app: &mut App, msg: String| {
                app.notify("Success", &msg);
            },
        ));
    }

    /// Returns true if dispatch can proceed, false if a task is already running.
    fn guard_dispatch(&self) -> bool {
        if self.task.is_some() {
            let trace = std::backtrace::Backtrace::force_capture();
            log::error!(
                "Attempted to dispatch a background task while one is already running. \
                 The UI action that triggered this should be disabled.\n{trace}"
            );
            return false;
        }
        true
    }
}
