name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build controller
      run: cargo build --verbose
      working-directory: tunnels
    - name: Build client
      run: cargo build --verbose
      working-directory: tunnelclient
    - name: Run controller tests
      run: cargo test --verbose
      working-directory: tunnels
